package:
  name: timesweeper
  version: "1.0.0"

source:
  git_url: https://github.com/SchriderLab/Timesweeper.git

requirements:
  build:
    - python
    - setuptools

  run:
   - numpy
   - scipy
   - matplotlib
   - pandas
   - scikit-allel
   - scikit-learn
   - tensorflow
   - keras
   - tqdm
   - slim
   - samtools
   - bcftools
   

about:
  home: https://github.com/SchriderLab/Timesweeper
  license: MIT